# Generated by Django 4.1 on 2022-09-25 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0004_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='experience',
            field=models.CharField(max_length=50),
        ),
    ]
