# Generated by Django 4.1 on 2022-09-25 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0005_alter_employee_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='Emp_ID',
            field=models.IntegerField(null=True),
        ),
    ]
