# Generated by Django 4.1 on 2022-09-14 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='details',
            name='age',
        ),
    ]
