# Generated by Django 4.1 on 2022-09-15 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0002_remove_details_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='age',
            field=models.IntegerField(default=0),
        ),
    ]
