# Generated by Django 4.1 on 2022-09-15 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0003_details_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='age',
            field=models.IntegerField(),
        ),
    ]
